// ============================================
// ArcDoc Enterprise - Clean Mockup Data
// ============================================
// Deletes ALL operational/demo data from the Turso database while KEEPING:
//   - users, roles, permissions, companies (auth/RBAC so login still works)
//   - schema/table structure (no DROP TABLE)
// Use when you want a clean, empty operational database.
//
// Run: npx tsx scripts/clean-mockup.ts

import { createClient } from '@libsql/client/web';
import 'dotenv/config';

const url = process.env.TURSO_DATABASE_URL || process.env.DATABASE_URL || '';
const token = process.env.TURSO_AUTH_TOKEN || '';

if (!url) {
  console.error('ERROR: TURSO_DATABASE_URL (or DATABASE_URL) environment variable is required.');
  process.exit(1);
}

const c = createClient({ url, authToken: token });

// ============================================
// MOCKUP / DEMO data — DELETED.
// Transactional records generated by full-seed (documents, requests, loans,
// transfers, audit, notifications, etc.). These are the fake demo records.
// ============================================
const MOCKUP_TABLES = [
  'audit_logs',
  'request_timeline',
  'request_documents',
  'request_messages',
  'request_attachments',
  'requests',
  'document_loans',
  'document_waitlist',
  'document_favorites',
  'document_comments',
  'document_relations',
  'document_tags',
  'document_attachments',
  'documents',
  'verifications',
  'generated_labels',
  'generated_documents',
  'signature_requests',
  'ocr_jobs',
  'inventory_items',
  'inventory_sessions',
  'disposal_proposals',
  'evidence_registry',
  'transfer_order_items',
  'transfer_orders',
  'withdrawal_orders',
  'location_history',
  'automation_rules',
  'report_definitions',
  'document_templates',
  'email_templates',
  'communication_history',
  'notifications',
  'scheduled_jobs',
  'process_verbals',
];

// ============================================
// CONFIGURATION / REFERENCE data — KEPT.
// These are needed for the platform to function (dropdowns, archive structure).
// ============================================
const CONFIG_TABLES = [
  'document_series',
  'archive_classification',
  'archival_funds',
  'retention_periods',
  'document_types',
  'nomenclatures',
  'archive_locations',
  'locations',
  'positions',
  'organizational_structure',
];


async function main() {
  console.warn('🧹 Cleaning mockup data...');
  let deleted = 0;
  const cleared: string[] = [];
  const missing: string[] = [];

  for (const t of MOCKUP_TABLES) {
    try {
      const r = await c.execute(`DELETE FROM ${t}`);
      deleted += Number(r.rowsAffected) || 0;
      cleared.push(t);
    } catch {
      missing.push(t); // table may not exist — ignore
    }
  }

  // Reset auto-increment sequences if any (SQLite AUTOINCREMENT)
  try {
    await c.execute(`DELETE FROM sqlite_sequence WHERE name IN (${MOCKUP_TABLES.map(() => '?').join(',')})`, MOCKUP_TABLES as any);
  } catch { /* ignore */ }

  console.warn(`✅ Deleted ${deleted} mockup rows across ${cleared.length} tables.`);
  if (missing.length) console.warn(`ℹ️  Skipped (table not found): ${missing.join(', ')}`);
  console.warn('✅ KEPT configuration/reference data:');
  console.warn(`   ${CONFIG_TABLES.join(', ')}`);
  console.warn('Login still works: admin@arcdoc.ro / Admin123!');

}

main().catch(e => {
  console.error('❌ Clean failed:', e.message);
  process.exit(1);
});
